Update ghcr.yaml

diff --git a/.github/workflows/ghcr.yaml b/.github/workflows/ghcr.yaml
--- a/.github/workflows/ghcr.yaml
+++ b/.github/workflows/ghcr.yaml
@@ -14,38 +14,38 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2
 
-      # - name: Read current version
-      #   id: get_version
-      #   run: |
-      #     if [ ! -f VERSION ]; then
-      #       echo "VERSION file not found. Exiting."
-      #       exit 1
-      #     fi
-      #     VERSION=$(cat VERSION)
-      #     echo "Current version: $VERSION"
-      #     echo "::set-output name=version::$VERSION"
+      - name: Read current version
+        id: get_version
+        run: |
+          if [ ! -f VERSION ]; then
+            echo "VERSION file not found. Exiting."
+            exit 1
+          fi
+          VERSION=$(cat VERSION)
+          echo "Current version: $VERSION"
+          echo "::set-output name=version::$VERSION"
 
-      # - name: Increment version
-      #   id: increment_version
-      #   run: |
-      #     VERSION=${{ steps.get_version.outputs.version }}
-      #     IFS='.' read -r major minor patch <<< "$VERSION"
-      #     patch=$((patch + 1))  # Increment the patch version
-      #     NEW_VERSION="$major.$minor.$patch"
-      #     echo "New version: $NEW_VERSION"
-      #     echo "$NEW_VERSION" > VERSION
-      #     echo "::set-output name=new_version::$NEW_VERSION"
+      - name: Increment version
+        id: increment_version
+        run: |
+          VERSION=${{ steps.get_version.outputs.version }}
+          IFS='.' read -r major minor patch <<< "$VERSION"
+          patch=$((patch + 1))  # Increment the patch version
+          NEW_VERSION="$major.$minor.$patch"
+          echo "New version: $NEW_VERSION"
+          echo "$NEW_VERSION" > VERSION
+          echo "::set-output name=new_version::$NEW_VERSION"
 
       - name: Log in to GitHub Container Registry
         run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
 
       - name: Build Docker image
         run: |
-          docker build DockerFileFolder/ -t ghcr.io/jbh043/acrdocker/my-app:latest
+          docker build DockerFileFolder/ -t ghcr.io/jbh043/acrdocker/my-app:${{ steps.increment_version.outputs.new_version }}
 
       - name: Push Docker image
         run: |
-          docker push ghcr.io/jbh043/acrdocker/my-app:latest
+          docker push ghcr.io/jbh043/acrdocker/my-app:${{ steps.increment_version.outputs.new_version }}
 
       # - name: Log in to Azure
       #   uses: azure/login@v1
